marketplace/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "core"
urlpatterns = [
	path('', views.index, name="index"),
	path('contact/', views.contact, name="contact"),
	path('signup/', views.signup, name="signup"),
	path('login/', auth_views.LoginView.as_view(
		template_name="core/login.html",
		authentication_form=LoginForm),
		name="login"),
]

marketplace/item/urls.py
from django.urls import path

from . import views

app_name = 'item'
urlpatterns = [
	path('', views.items, name="items"),
	path('new/', views.new, name="new"),
	path('<int:pk>/', views.detail, name="detail"),
	path('<int:pk>/edit/', views.edit, name="edit"),
	path('<int:pk>/delete/', views.delete, name="delete"),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder': 'Your email address',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Repeat password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))


class LoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

marketplace/core/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from item.models import Category, Item
from .forms import SignupForm


def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form
	})


def index(request):
	items = Item.objects.filter(is_sold=False)[0:6]
	categories = Category.objects.all()

	return render(request, 'core/index.html', {
		'categories': categories,
		'items': items
	})


def contact(request):
	return render(request, 'core/contact.html')

marketplace/core/templates/core/contact.html
{% extends 'base.html' %}

{% block title %}
Contact
{% endblock %}

{% block content %}
<h1>Contact page!</h1>
{% endblock %}

marketplace/core/templates/core/index.html
{% extends 'base.html' %}

{% block title %}
Main
{% endblock %}

{% block content %}
	<div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
		<h2 class="mb-12 text-2xl text-center">Newest items</h2>
		<div class="grid grid-cols-3 gap-3">
			{% for item in items %}
			<div>
				<a href="{% url 'item:detail' item.id %}">
					<div><img src="{{ item.image.url }}" class="rounded-t-xl" alt=""></div>
				</a>
				<div class="p-6 bg-white rounded-b-xl">
					<h2 class="text-2xl">{{ item.name }}</h2>
					<p class="text-gray-500">Price: {{ item.price }}</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class="mb-12 text-2xl text-center">Categories</h2>
		
		<div class="grid grid-cols-3 gap-3">
			{% for category in categories %}
			<div>
				<div class="p-6 bg-white rounded-b-xl">
					<h2 class="text-2xl">{{ category.name }}</h2>
					<p class="text-gray-500">{{ category.items.count }} items</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

marketplace/core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}
Log-in
{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
	<h1 class="mb-6 text-3xl">Log-in</h1>
	<form method="post" action=".">
		{% csrf_token %}
		<div class="mb-3">
			<label for="" class="inline-block mb-2">Username</label><br>
			{{ form.username }}
		</div>
		<div class="mb-3">
			<label for="" class="inline-block mb-2">Password</label><br>
			{{ form.password }}
		</div>
		{% if form.errors or form.non_field_errors %}
		<div class="mb-3 p-6 bg-red-100 rounded-xl">
			{% for field in form %}
				{{ field.errors }}
			{% endfor %}
			{{ form.non_field_errors }}
		</div>
		{% endif %}
		<button class="py-4 px-8 text-lg bg-teal-500 hover:text-teal-700 rounded-xl text-white">Submit</button>
	</form>
</div>
{% endblock %}

marketplace/core/templates/core/signup.html
{% extends 'base.html' %}

{% block title %}
Sign-up
{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
	<h1 class="mb-6 text-3xl">Sign up</h1>
	<form method="post" action=".">
		{% csrf_token %}
		<div class="mb-3">
			<label for="" class="inline-block mb-2">Username</label><br>
			{{ form.username }}
		</div>
		<div class="mb-3">
			<label for="" class="inline-block mb-2">Email</label><br>
			{{ form.email }}
		</div>
		<div class="mb-3">
			<label for="" class="inline-block mb-2">Password</label><br>
			{{ form.password1 }}
		</div>
		<div class="mb-3">
			<label for="" class="inline-block mb-2">Repeat password</label><br>
			{{ form.password2 }}
		</div>
		{% if form.errors or form.non_field_errors %}
		<div class="mb-3 p-6 bg-red-100 rounded-xl">
			{% for field in form %}
				{{ field.errors }}
			{% endfor %}
			{{ form.non_field_errors }}
		</div>
		{% endif %}
		<button class="py-4 px-8 text-lg bg-teal-500 hover:text-teal-700 rounded-xl text-white">Submit</button>
	</form>
</div>
{% endblock %}