marketplace/conversation/urls.py
from django.urls import path


from . import views

app_name = 'conversation'
urlpatterns = [
	path('', views.inbox, name='inbox'),
	path('<int:pk>/', views.detail, name='detail'),
	path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

marketplace/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "core"
urlpatterns = [
	path('', views.index, name="index"),
	path('contact/', views.contact, name="contact"),
	path('signup/', views.signup, name="signup"),
	path('login/', auth_views.LoginView.as_view(
		template_name="core/login.html",
		authentication_form=LoginForm),
		name="login"),
]

marketplace/dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'
urlpatterns = [
	path('', views.index, name="index"),
]

marketplace/item/urls.py
from django.urls import path

from . import views

app_name = 'item'
urlpatterns = [
	path('', views.items, name="items"),
	path('new/', views.new, name="new"),
	path('<int:pk>/', views.detail, name="detail"),
	path('<int:pk>/edit/', views.edit, name="edit"),
	path('<int:pk>/delete/', views.delete, name="delete"),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder': 'Your email address',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Repeat password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))


class LoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

marketplace/core/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from item.models import Category, Item
from .forms import SignupForm


def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form
	})


def index(request):
	items = Item.objects.filter(is_sold=False)[0:6]
	categories = Category.objects.all()

	return render(request, 'core/index.html', {
		'categories': categories,
		'items': items
	})


def contact(request):
	return render(request, 'core/contact.html')

marketplace/core/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>Marketplace | {% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Marketplace</a>

            <div class="space-x-6">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                    <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>